//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public int AppealCode { get; set; }
        public int UserID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Description { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
