USE [master]
GO

/****** Object:  Database [TG]    Script Date: 09.02.2024 22:41:46 ******/
CREATE DATABASE [TG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TechnoGuide', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.GIRFANOV\MSSQL\DATA\TG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TechnoGuide_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.GIRFANOV\MSSQL\DATA\TG_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TG] SET ARITHABORT OFF 
GO

ALTER DATABASE [TG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TG] SET RECOVERY FULL 
GO

ALTER DATABASE [TG] SET  MULTI_USER 
GO

ALTER DATABASE [TG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TG] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TG] SET QUERY_STORE = ON
GO

ALTER DATABASE [TG] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [TG] SET  READ_WRITE 
GO

